/**
 * WebCrypto API AES-256-GCM Encryption Utility
 * Used for End-to-End Encryption (E2EE) of local Dexie database and remote sync payloads.
 */

// Number of PBKDF2 iterations for key derivation. Higher is more secure but slower.
const PBKDF2_ITERATIONS = 100_000;
const SALT_SIZE = 16;
const IV_SIZE = 12;

let activeCryptoKey: CryptoKey | null = null;
let activeIsEncrypted = false;

export function setGlobalCryptoKey(
  key: CryptoKey | null,
  isEncrypted: boolean,
) {
  activeCryptoKey = key;
  activeIsEncrypted = isEncrypted;
}

export function getGlobalCryptoKey() {
  return { key: activeCryptoKey, isEncrypted: activeIsEncrypted };
}

/**
 * Generates a random salt (Base64 string) for new users.
 */
export function generateSalt(): string {
  if (typeof window === "undefined" || !window.crypto) return "";
  const salt = window.crypto.getRandomValues(new Uint8Array(SALT_SIZE));
  return btoa(String.fromCharCode(...salt));
}

/**
 * Derives an AES-GCM CryptoKey from a raw password string and a Base64 salt.
 * @param password The plaintext password provided by the user
 * @param base64Salt The salt stored in the database for this user
 * @returns A CryptoKey ready for AES-GCM encryption/decryption
 */
export async function deriveKey(
  password: string,
  base64Salt: string,
): Promise<CryptoKey> {
  const enc = new TextEncoder();

  // Import the raw password as key material
  const keyMaterial = await window.crypto.subtle.importKey(
    "raw",
    enc.encode(password),
    { name: "PBKDF2" },
    false,
    ["deriveBits", "deriveKey"],
  );

  // Decode the salt
  const saltBuffer = Uint8Array.from(atob(base64Salt), (c) => c.charCodeAt(0));

  // Derive the AES-GCM key
  return await window.crypto.subtle.deriveKey(
    {
      name: "PBKDF2",
      salt: saltBuffer,
      iterations: PBKDF2_ITERATIONS,
      hash: "SHA-256",
    },
    keyMaterial,
    { name: "AES-GCM", length: 256 },
    false, // Do not allow extracting the raw key for maximum security
    ["encrypt", "decrypt"],
  );
}

/**
 * Encrypts a plain JS object into a Base64 AES-GCM ciphertext payload.
 * @param data The JSON object to encrypt
 * @param key The derived AES-GCM CryptoKey
 * @returns A Base64 string containing both the IV and the Encrypted Payload
 */
export async function encryptData(
  data: unknown,
  key: CryptoKey,
): Promise<string> {
  const enc = new TextEncoder();
  const iv = window.crypto.getRandomValues(new Uint8Array(IV_SIZE));
  const encodedData = enc.encode(JSON.stringify(data));

  const encryptedBuffer = await window.crypto.subtle.encrypt(
    {
      name: "AES-GCM",
      iv: iv,
    },
    key,
    encodedData,
  );

  // Combine IV and Ciphertext into a single buffer
  const combined = new Uint8Array(iv.length + encryptedBuffer.byteLength);
  combined.set(iv, 0);
  combined.set(new Uint8Array(encryptedBuffer), iv.length);

  // Return as Base64 string
  return btoa(String.fromCharCode(...combined));
}

/**
 * Decrypts a Base64 AES-GCM payload back into a JS object.
 * @param base64Payload The string generated by encryptData
 * @param key The derived AES-GCM CryptoKey
 * @returns The original parsed JSON object
 */
export async function decryptData<T>(
  base64Payload: string,
  key: CryptoKey,
): Promise<T> {
  const combined = Uint8Array.from(atob(base64Payload), (c) => c.charCodeAt(0));

  // Extract the IV (first 12 bytes) and ciphertext
  const iv = combined.slice(0, IV_SIZE);
  const data = combined.slice(IV_SIZE);

  try {
    const decryptedBuffer = await window.crypto.subtle.decrypt(
      {
        name: "AES-GCM",
        iv: iv,
      },
      key,
      data,
    );

    const dec = new TextDecoder();
    return JSON.parse(dec.decode(decryptedBuffer)) as T;
  } catch (error) {
    console.error("Decryption failed. Invalid key or corrupted data.", error);
    throw new Error("Failed to decrypt data.");
  }
}
